server:
  port: 7001

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，负责维护服务实例，不需要检索服务
    fetch-registry: false
    #会将链接中的eureka7002.com注册到DS Replicas中
    service-url:
      #      defaultZone: http://eureka7001.com:7002/eureka/ 单机
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    # 关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false
